### ISSUE TITLE
Foreman 'export' doesn't work with Ruby 3.2

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1085]
```
00:00 deploy:update_systemd_scripts
      01 script/export_procfiles_to_systemd_prod.sh
      01 /usr/local/rvm/gems/ruby-3.2.2/gems/foreman-0.87.2/lib/foreman/export/base.rb:86:in `rescue in chown': undefined method `exists?' for File:Class (NoMe…
      01
      01     error("Could not chown #{dir} to #{user}") unless File.writable?(dir) || ! File.exists?(dir)
      01                                                                                    ^^^^^^^^
      01 Did you mean?  exist?
      01 	from /usr/local/rvm/gems/ruby-3.2.2/gems/foreman-0.87.2/lib/foreman/export/base.rb:83:in `chown'
      01 	from /usr/local/rvm/gems/ruby-3.2.2/gems/foreman-0.87.2/lib/foreman/export/base.rb:49:in `export'
      01 	from /usr/local/rvm/gems/ruby-3.2.2/gems/foreman-0.87.2/lib/foreman/export/systemd.rb:7:in `export'
      01 	from /usr/local/rvm/gems/ruby-3.2.2/gems/foreman-0.87.2/lib/foreman/cli.rb:62:in `export'
      01 	from /usr/local/rvm/gems/ruby-3.2.2/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/command.rb:27:in `run'

```

**Comment by jcoyne** [comment]
Upstream is https://github.com/ddollar/foreman/issues/794

**Comment by thatbudakguy** [comment]
It's been a year since the last commit to foreman. Seem to be many folks suggesting abandoning it in the issues. [Some alternatives to foreman](https://github.com/ddollar/foreman/pull/780#issuecomment-1539646480) are mentioned in a comment.

**Comment by jcoyne** [comment]
@thatbudakguy none of those alternatives support the export command, which is the one area here where we are having trouble.

**Comment by thatbudakguy** [comment]
Maybe the best solution: write our own script that does the equivalent of `foreman export`.
